-- Generated by illogical-impulse Displays settings.
-- Hand edits may be overwritten by the settings app.
hl.monitor({ output = "eDP-1", mode = "2560x1600@60.00", position = "0x0", scale = 1, vrr = 1 })
