-- Generated by Skill Shell Displays settings.
-- Hand edits may be overwritten by the settings app.
hl.monitor({ output = "eDP-1", mode = "2560x1600@240.00", position = "0x0", scale = 1, vrr = 1 })
hl.monitor({ output = "HDMI-A-1", mode = "2560x1440@59.95", position = "2560x0", scale = 1, vrr = 0 })
