vnoremap <C-c> "+y
inoremap <C-v> <F10><C-r>+<F10>
nmap <leader>o o<Esc>d$
nmap <leader>O O<Esc>d$
nmap <leader>c "_c
nmap <leader>d "_d
vnoremap <leader>p "_dP
vnoremap <leader>c "_c
map <leader><Bslash> :NERDTreeToggle<CR>
