#!/usr/bin/env bash

CONFIG_FILES="$HOME/.config/waybar/config $HOME/.config/waybar/style.css $HOME/.config/waybar/styles/ $HOME/.config/waybar/styles/**/* $HOME/.config/waybar/custom_modules/"

trap "pkill waybar" EXIT

while true; do
    waybar &
    inotifywait -e create,modify $CONFIG_FILES
    pkill waybar
done
