#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

if test -z "$DBUS_SESSION_BUS_ADDRESS"; then
  eval 'dbus-launch --sh-syntax --exit-with-session'
fi

eval $(gnome-keyring-daemon --start) &
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# disable bell for x applications
xset b off

# xautolock -time 30 -locker "sklock" -corners -000 -cornerdelay 3 &
# xss-lock sklock &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

xrdb -load ~/.config/X11/Xresources

numlockx on &
nitrogen --restore &
copyq &
redshift -l '52.090736:5.121420' &
slayout &
picom -b
restart-flashfocus &
swapcaps &
sxhkd &
# notion-app &
notion-calendar-electron &
flyterm &

exec awesome
