input {
  kb_layout = us,ir
  kb_options = grp:shifts_toggle,caps:escape
  kb_variant =
  kb_model =
  kb_rules =

  touchpad {
    natural_scroll = true
    scroll_factor = 0.3
  }

  sensitivity = 0
  follow_mouse = 2
}

general {
  gaps_in = 5
  gaps_out = 5
  border_size = 1
  col.active_border = rgba(FFFFFFFF)
  col.inactive_border = rgba(000000FF)

  layout = master
}

decoration {
  rounding = 8
  active_opacity = 1
  inactive_opacity = 1

  shadow {
    enabled = false
    range = 2
    render_power = 1
    color = rgba(000000ff)
  }

  blur {
    enabled = false
    size = 3
    passes = 1
  }
}

dwindle {
  preserve_split = true
}

master {
  new_status = slave
  new_on_top = false
  mfact = 0.5
}

gesture = 3, horizontal, workspace

device {
  name = epic-mouse-v1
  sensitivity = -0.5
}

misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
  mouse_move_enables_dpms = true
}

binds {
  allow_workspace_cycles = true
  hide_special_on_workspace_change = true
}
