background {
    monitor =
    path = ~/pics/wallpaper.png
    blur_passes = 2
    blur_size = 5
}

input-field {
    monitor =
    size = 50, 50
    outline_thickness = 2
    dots_size = 0.1
    dots_spacing = 0.5
    outer_color = rgba(ffffff77)
    inner_color = rgba(1a1a1a00)
    font_color = rgba(ffffff77)
    fade_on_empty = true
    placeholder_text =
    position = 0, -60
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_size = 100
    font_family = XP Ziba Bold
    color = rgba(ffffffaa)
    position = 0, 100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"%d %B"
    font_size = 20
    font_family = XP Ziba Bold
    color = rgba(c0c0c0ff)
    position = 0, 150
    halign = center
    valign = center
}
