monitor = , highres, auto, 1

env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_QPA_PLATFORM,wayland;xcb
env = GDK_BACKEND,wayland,x11
env = MOZ_ENABLE_WAYLAND,1
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

env = ILLOGICAL_IMPULSE_VIRTUAL_ENV,~/.local/state/quickshell/.venv

source = ~/.config/hypr/general.conf
source = ~/.config/hypr/animation.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/autostart.conf

debug {
  disable_logs = false
}
