windowrule = match:class ^([Bb]rave-browser|[Ff]irefox|[Cc]hromium|[Ff]irefox Beta)$, workspace 2
windowrule = match:class ^([Cc]ode|[Cc]ursor|dev\.zed\.Zed)$, workspace 3
windowrule = match:class ^([Ss]lack)$, workspace 7
windowrule = match:class ^([Ss]potify)$, workspace 8
windowrule = match:class ^(org\.telegram\.desktop|TelegramDesktop)$, workspace 9

windowrule = match:class ^(pavucontrol)$, float on, center on
windowrule = match:class ^(blueman-manager)$, float on, center on
windowrule = match:class ^(zenity)$, float on, center on
windowrule = match:class ^(Gpick|Gcolor3|xcolor)$, float on
windowrule = match:title ^(Open File|Save File|branchdialog|Picture-in-Picture|Picture in picture)$, float on

windowrule = match:class ^(flyterm)$, float on, size 700 500, center on, border_color rgb(000000), workspace special:term
windowrule = match:class ^([Zz]athura)$, float on, fullscreen on
