#!/bin/bash

# tools
alias figma='open_d "https://figma.com"'
alias loc3='open_d "https://localhost:3000/"'
alias tenf='open_d "https://www.edclub.com/sportal/program-3.game"'
alias g='open_d "https://github.com/frontendmonster"'

alias tg='cd $HOME/downloads/Telegram\ Desktop'
alias dwn='cd $HOME/downloads'
alias dnd='cd $HOME/dev/dnd'
alias docs='cd $HOME/docs/'
alias thes='cd $HOME/dev/thesis/'
alias books='cd $HOME/docs/books'
alias cheats='cd $HOME/dev/rewire/initiator/resources/'

INFO="$HOME/docs/info"
alias cards='vim $INFO/card.yml'
alias infos='vim $INFO/info.yml'

alias libs='cd $HOME/dev/libs'
alias devs='cd $HOME/dev/projects'
alias rewire='cd $HOME/dev/rewire'

alias fem='cd $HOME/dev/projects/fullstacks'
alias bot='cd $HOME/dev/projects/guardian'
alias sm='cd $HOME/dev/smartsept/'
alias sma='cd $HOME/dev/smartsept/app'

FSK="$HOME/fullstacks"
alias f='cd $FSK'
alias fdev='cd $FSK/projects'
alias fexp='cd $FSK/exploration'
alias codeit='cd $FSK/projects/codeit'

EG="$HOME/dev/eg"
alias eg='cd $EG'
alias sus='cd $EG/user-service'

alias cal=   'open_d "https://calendar.google.com/calendar/u/2/r"'
alias docs=  'open_d "https://user.staging.estateguru.co/documentation/index.html"'
alias invs=  'open_d "https://projects.invisionapp.com/d/main#/projects/prototypes/21369560"'
alias stand= 'open_d "https://meet.google.com/het-feup-ygi?authuser=2"'
alias sprint='open_d "https://estateguru.atlassian.net/secure/RapidBoard.jspa?rapidView=5&projectKey=EGNEW"'

