#!/bin/bash

export MONSTER='/home/monster'

alias monster='cd $MONSTER'
alias tuts='cd $MONSTER/videos/tutorials/'
alias tg='cd $MONSTER/downloads/Telegram\ Desktop'
alias dwn='cd $MONSTER/downloads'
alias dnd='cd $MONSTER/projects/dnd'
alias doc='cd $MONSTER/documents/'
alias profile='cd $MONSTER/documents/info'
alias parma='cd $MONSTER/projects/dnd/thesis/parma'
alias books='cd $MONSTER/books'

alias cards='vim $MONSTER/documents/info/card.yml'

alias libs='cd $HOME/dev/libs'
alias devs='cd $HOME/dev/projects'
alias rewire='cd $HOME/dev/rewire'
alias fsk='cd $HOME/fullstacks/dnd'

alias dotfiles='cd $HOME/dev/rewire/initiator'
alias fem='cd $HOME/dev/projects/fullstacks'
alias bot='cd $HOME/dev/projects/guardian'
alias sm='cd $HOME/smartsept/smartsept && s'

