[general]
import = [
  "~/.config/alacritty/color.toml",
  "~/.config/alacritty/layout.toml",
  "~/.config/alacritty/typography.toml",
  "~/.config/alacritty/mouse.yml",
  "~/.config/alacritty/key-binding.toml"
]
live_config_reload = true
working_directory = "None"

[cursor]
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "Off"
shape = "Block"

[cursor.vi_mode_style]
blinking = "On"
shape = "Block"

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
