[debug]
# Display the time it takes to redraw each frame.
render_timer = false
# Keep the log file after quitting Alacritty.
persistent_logging = false
# Print all received window events.
print_events = false
log_level = Warn
